### ISSUE TITLE
XML parse error in ruby 3.0.0 docs

### ISSUE THREAD

**Issue by yourpalal** [rubydocs/app#15]
https://rubydocs.org/d/ruby-3-0-0/?q=DateTime shows that the xml parse of docs failed in some way.
2.x.x versions seem to still be working (eg: https://rubydocs.org/d/ruby-2-7-2/).

Personally, I can use an older version and that works fine for me, but I thought I might as well bring this to your attention

Thanks for this great service 😄

**Comment by manuelmeurer** [comment]
Thanks, @yourpalal! I'm working on getting it fixed.

**Comment by manuelmeurer** [comment]
Fixed!
