### ISSUE TITLE
Docs are no longer available

### ISSUE THREAD

**Issue by dmorgan-fa** [rubydocs/app#16]
Hey, just in case you're not aware, all docs seem to report either:
- a key error: does not exist (i.e. [Capybara](https://rubydocs.org/d/capybara-3-34-0/))
- "Docs are being generated" splash screen ([Nokogiri](https://rubydocs.org/nokogiri-1-11-1/))
- "The change you wanted was rejected"/"No access" error message

![image](https://user-images.githubusercontent.com/60140349/110611368-12264c80-8187-11eb-8f35-d20eac5f25a5.png)
![image](https://user-images.githubusercontent.com/60140349/110611312-0175d680-8187-11eb-8fe8-d91db838e886.png)
![image](https://user-images.githubusercontent.com/60140349/110611225-ed31d980-8186-11eb-929c-bfc524eefe61.png)

Thanks!

**Comment by manuelmeurer** [comment]
Oh boy, thanks for letting me know. I'll have a look at what happened...

**Comment by manuelmeurer** [comment]
Ok, all existing docs should be back up!
I'm doing a rewrite right now, so some newer docs have not been generated yet (e.g. Nokogiri 1.11.1), but they will be online soon! :)

**Comment by dmorgan-fa** [comment]
Nice one Manuel! Thanks for the quick turn around! Really valuable resource you're providing, so I'm glad to see it back up and running 👍
